# Most capitals allowed in a message. Set to -1 to disable
maxCapitals: 10
# Most consecutive of the same character allowed in a message. Set to 0 to disable
maxFlood: 5
# Time in milliseconds required between messages. Set to 0 to disable
spamCooldown: 2500
# Number of characters that can be different and still be censored in a word. Set to 0 to disable
censorDistance: 2

# List of things being used to replace "." in an IP
# For example, 127(dot)0(dot)0(dot)1
# Parentheses and periods must be prefaced with a \\ i.e. "\\(dot\\)"
adsplits:
  - "\\."
  - ","
  - "\\(dot\\)"
  - "\\(\\.\\)"
  - "\\(,\\)"
  - "dot"

# List of words that players can choose if they want censored
softCensor:
  - "anal"
  - "anus"
  - "arse"
  - "asshole"
  - "asshat"
  - "bitch"
  - "boob"
  - "ballsack"
  - "bastard"
  - "blowjob"
  - "boner"
  - "breats"
  - "butt"
  - "cock"
  - "clit"
  - "clitoris"
  - "cunilingus"
  - "cunt"
  - "damn"
  - "dick"
  - "dildo"
  - "dammit"
  - "ejaculate"
  - "faggot"
  - "fuck"
  - "fatass"
  - "gangban"
  - "goddamn"
  - "horny"
  - "masturbate"
  - "jizz"
  - "mofo"
  - "orgasm"
  - "porn"
  - "penis"
  - "phuck"
  - "phuq"
  - "piss"
  - "pornography"
  - "prick"
  - "pussy"
  - "rectum"
  - "retard"
  - "rimjob"
  - "rimming"
  - "shit"
  - "schlong"
  - "scrotum"
  - "semen"
  - "slut"
  - "titty"
  - "titties"
  - "tiddies"
  - "tiddy"
  - "testicle"
  - "viagra"
  - "vagina"
  - "whore"
  - "fag"
  - "motherfuck"

# List of words that will be censored regardless of player options
hardCensor:
  - "nigger"
  - "nigga"
  - "nibba"
  - "niger"
  - "nig"
  - "chink"
  - "boomer"

# List of words that were censored and shouldn't be
falsePositives:
  - "enable"
  - "longer"
  - "book"
  - "break"
  - "words"
  - "while"
  - "prior"
  - "create"
  - "opens"
  - "tick"
  - "lick"
  - "those"
  - "power"
  - "owner"
  - "kick"
  - "sends"
  - "nick"
  - "world"
  - "seen"
  - "create"
  - "where"
  - "perish"
  - "whois"
  - "switch"
  - "regard"
  - "changes"
  - "second"
  - "there"