name: CubeChat
main: com.cubepalace.cubechat.CubeChat
author: RoboticPlayer
version: 0.1
depend: [ProtocolLib]

commands:
  clearchat:
    description: Clears the chat
    usage: /clearchat [-s]
  mutechat:
    description: Mutes and unmutes the chat
    usage: /mutechat [-s]
  cubechat:
    description: Main plugin command
  shadowmute:
    description: Mutes someone without them knowing
    usage: /shadowmute <player>
  togglefilter:
    description: Changes your filter status
    
permissions:
  cubechat.*:
    description: Gives access to all CubeChat commands
    children:
      cubechat.clearchat: true
      cubechat.clearchat.exempt: true
      cubechat.clearchat.silent: true
      cubechat.mutechat: true
      cubechat.mutechat.exempt: true
      cubechat.mutechat.silent: true
      cubechat.mutechat.read: true
      cubechat.cmd: true
      cubechat.reload: true
      cubechat.shadowmute: true
      cubechat.shadowmute.read: true
      cubechat.shadowmuted: true
      cubechat.caps.exempt: true
      cubechat.flood.exempt: true
      cubechat.spam.exempt: true
      cubechat.togglefilter: true
      cubechat.checkfilter: true
      cubechat.forcefilter: true
  cubechat.clearchat:
    description: Allows you to clear chat
  cubechat.clearchat.exempt:
    description: Your chat will not get cleared
  cubechat.clearchat.silent:
    description: You can use the "-s" argument for silent clear
  cubechat.mutechat:
    description: Allows you to mute/unmute the chat
  cubechat.mutechat.exempt:
    description: Your chat will not be muted
  cubechat.mutechat.silent:
    description: You can use the "-s" argument for silent mute/unmute
  cubechat.mutechat.read:
    description: You can read attempted messages from players while the chat is muted
  cubechat.cmd:
    description: Allows you to do /cubechat
  cubeechat.reload:
    description: Lets you reload the plugin
  cubechat.shadowmute:
    description: Allows you to shadowmute people
  cubechat.shadowmute.read:
    description: Allows you to read messages from shadowmuted players
  cubechat.shadowmuted:
    description: Allows you to check if someone is shadowmuted
  cubechat.caps.exempt:
    description: Your messages won't be lowercased for too many capitals
  cubechat.flood.exempt:
    description: Your messages won't be shortened for flood
  cubechat.spam.exempt:
    description: You won't have a message cooldown
  cubechat.togglefilter:
    description: Ability to toggle your filter
  cubechat.checkfilter:
    description: Ability to check if a player has their filter on
  cubechat.forcefilter:
    description: Ability to force a player's filter on or off